apiVersion: v1
kind: Secret
metadata:
  name: {{ include "craton-hsm.fullname" . }}-security
  labels:
    {{- include "craton-hsm.labels" . | nindent 4 }}
type: Opaque
stringData:
  security.toml: |
    [security]
    pin_min_length = {{ .Values.config.pinMinLength }}
    pin_max_length = {{ .Values.config.pinMaxLength }}
    max_failed_logins = {{ .Values.config.maxFailedLogins }}
