from typing import Tuple

class HsmClient:
    def __init__(
        self,
        mode: str = "local",
        *,
        base_url: str | None = ...,
        token: str | None = ...,
        client_cert: Tuple[str, str] | None = ...,
        verify: str | bool = ...,
    ) -> None: ...

    @property
    def mode(self) -> str: ...

    def capabilities(self) -> dict: ...

    def sign(self, handle: int, mechanism: str, data: bytes) -> bytes: ...
    def verify(self, handle: int, mechanism: str, data: bytes, signature: bytes) -> bool: ...
    def encapsulate(self, handle: int, mechanism: str) -> Tuple[bytes, bytes]: ...
    def decapsulate(self, handle: int, mechanism: str, ciphertext: bytes) -> bytes: ...
